# Generated by Django 4.1.5 on 2023-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musixapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmname', models.CharField(max_length=250)),
                ('musicname', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('singers', models.CharField(max_length=250)),
                ('audio', models.FileField(upload_to='')),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
