# Generated by Django 4.1.5 on 2023-07-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musixapp', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='musixapp/static')),
            ],
        ),
    ]
