# Generated by Django 4.1.5 on 2023-07-15 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musixapp', '0004_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileimage',
        ),
        migrations.AddField(
            model_name='songupload',
            name='likes',
            field=models.ManyToManyField(related_name='song_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
